[package]
name = "almondala"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.76"
rayon = "1.10.0"
wasm-bindgen = "0.2.99"
web-sys = {version = "0.3.76", features = ["ImageData", "CanvasRenderingContext2d"] }
